"""Edit date type

Revision ID: 2b02e08c3c92
Revises: 40d0aa892a51
Create Date: 2025-05-19 22:09:12.193664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b02e08c3c92'
down_revision: Union[str, None] = '40d0aa892a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('events', 'day_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('day_month', sa.VARCHAR(length=5), nullable=False))
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
